// @ts-nocheck
// This file is auto-generated by TanStack Router. Do not edit manually.
import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = rootRoute.addChildren([IndexRoute])
